### PR TITLE
closes #1293. allows aliases that start with @ to be caught as internal

### LINKED ISSUE #1293: [import/order] Aliases that start with @ get incorrectly grouped
Given that Typescript is going to switch over to ESLint as its main linting tool, I wanted to try to get my project at work switched over. In Typescript, you can define paths. Paths allow you to define import paths, i.e. `@my-alias/fn` could actually point to `src/my-folder/fn.ts`. 

In my project, currently using TSLint, we have external, aliases, parent, sibling as our import sort order. After trying to get a test case working with ESLint, it seems like this plugin incorrectly associates aliases that start with `@` to external modules, since it thinks they are "scoped".

I don't know the solution to this, however, I would be open to putting in a PR if someone can provide some insight into solving this? 

I have tried to create a minimal repro, but it seems like code-sandbox won't give access to the terminal... But this example does fail, saying that you can't have newlines between groups on the lodash import. https://codesandbox.io/s/7m5zpmxo90

### PR DESCRIPTION
**Pull request by jeffshaver**
@ljharb as we talked about in the issue, here is the fix. Please let me know if there are any issues. Or if you think we need more tests for this case. I added one. There were already a ton that didn't pass and didn't think I should fix them in this PR.

Fixes #1293. Unblocked by #1295.

### CODE REVIEW

File: src/core/importType.js [hunk 1]
```diff
@@ -8,8 +8,8 @@ function constant(value) {
   return () => value
 }
 
-function baseModule(name) {
-  if (isScoped(name)) {
+function baseModule(name, path) {
+  if (isScoped(name, path)) {
```
Comment (ljharb) [inline src/core/importType.js]: i don't think it makes sense to make `isScoped` check `isExternalPath`; i think all the places currently calling `isScoped` should be explicitly handling `isExternalPath` first.

Comment (jeffshaver) [reply src/core/importType.js]: I can do that. It does seem that "scoped" packages have a connotation meaning "external". So I thought it would be fine putting it in `isScoped` because scoped modules have to be external. Will update shortly

Comment (jeffshaver) [reply src/core/importType.js]: Actually... I don't even know how to solve this? Move the `isScoped` check down underneath `isInternalModule`in the lodash.cond call? The problem I am seeing is that isScoped means external, but isExternalModule doesn't check it. It is checked by the lodash.cond call

Comment (jeffshaver) [reply src/core/importType.js]: Seems like moving the internal check above scoped and external solved that problem and let me revert most of the other changes

**Comment by jeffshaver** [comment]
@ljharb updated per your comments. Appreciate you looking at this!

File: src/core/importType.js (hunk 1 above)
Comment (ljharb) [reply src/core/importType.js]: Scoped packages are the same as anything in node_modules; they're things installed from npm. I don't think "scoped" means "external".

**Comment by jeffshaver** [comment]
@ljharb anything I can do to help unbreak master?

**Comment by ljharb** [comment]
@jeffshaver open another PR that fixes the tests? :-D

**Comment by jeffshaver** [comment]
@ljharb. I'll take a look later today to see if I can fix some

**Comment by jeffshaver** [comment]
@ljharb since my other pr got merged (thanks! sorry we couldn't fix that one test), i rebased my branch with upstream master. just wanted to let you know

**Comment by ljharb** [comment]
@jeffshaver oh we fixed it! thanks for the PR, and the ping.

File: src/core/importType.js [hunk 2]
```diff
@@ -76,9 +77,9 @@ function isRelativeToSibling(name) {
 const typeTest = cond([
   [isAbsolute, constant('absolute')],
   [isBuiltIn, constant('builtin')],
+  [isInternalModule, constant('internal')],
   [isExternalModule, constant('external')],
   [isScoped, constant('external')],
-  [isInternalModule, constant('internal')],
```
Comment (ljharb) [inline src/core/importType.js]: This looks good, but there is the possibility this will be a breaking change - however, since it doesn't break any tests, and since it's unlikely anyone is depending on the *inability* to mark an external module as "internal", it's probably fine.

**Comment by jeffshaver** [comment]
@ljharb appreciate it! When do you think a new version will be released with these changes?

**Comment by ljharb** [comment]
Probably not super quickly; ping me again in a week if it’s not done by then.

**Comment by laozhu** [comment]
Have the PR been released? My '@' alias imports are still 'unknown' type with the latest eslint-plugin-import.

**Comment by ljharb** [comment]
@laozhu yes, if you click on the commit https://github.com/benmosher/eslint-plugin-import/commit/651829d6a2862b8fa2e33426421a5dba526e4cdb you can see it's in 2.17.0 and higher.
