### PR TITLE
`no-commonjs`: Fix false positive when `exports` is in scope

### LINKED ISSUE #940: no-commonjs: Allow assigning to a variable called exports
`exports` should only be disallowed assignment if it's the "global" `exports` of CJS, not any old variable named `exports`.

```js
function someFunc() {
  const exports = someComputation();

  expect(exports.someProp).toEqual({ a: 'value' });
}
```

image

### PR DESCRIPTION
**Pull request by adrianhelvik**
I've added a fix for false positives for no-commonjs when `exports` is in scope.

Fixes #940.

### CODE REVIEW

File: src/rules/no-commonjs.js [hunk 1]
```diff
@@ -36,7 +36,12 @@ module.exports = {
 
         // exports.
         if (node.object.name === 'exports') {
-          context.report({ node, message: EXPORT_MESSAGE })
+          const isInScope = context.getScope()
+            .variables
+            .some(variable => variable.name === 'exports')
+          if (! isInScope) {
```
Comment (ljharb) [inline src/rules/no-commonjs.js]: please remove the space between the `!` and `isInScope`
