### PR TITLE
Fix interpreting some external modules being interpreted as internal modules

### LINKED ISSUE #793: import/order fails after updating a dependency (redux-saga)
When using `redux-saga@0.14.4` everything is fine
But fails when using `redux-saga@0.14.5`

I think the reason for this to fails is this PR: https://github.com/redux-saga/redux-saga/pull/895

-----

Error message:

`./userSaga import should occur before import of redux-saga/effects             import/order`

Code: 

```js
import { fork } from 'redux-saga/effects';

import connectionFlow from './userSaga';
```

### PR DESCRIPTION
**Pull request by Ephys**
Checklist:

- [x] write tests
- [x] implement feature/fix bug
- [x] ~update docs~
- [x] make a note in change log

Fixes #793

It was fixed by making `isExternalPath` search for  `<module_dir>/<package_name>` (e.g. `node_modules/redux-saga`) instead of `<module_dir>/<package_name>/<file_name>` (e.g. `node_modules/redux-saga/effects`) in the resolved path.

I'd argue that the new solution is still not optimal, as it will fail if an external module has a `main` field which links to another external module.

Should we instead just check that the beginning of the resolved path is the resolved path for the external module folder ? I can make a PR with that alternate solution if requested.

You also might want to check the way I implemented the tests as they might not be an optimal solution.

Edit: The build is failing but was already failing before I started writing code, should I be worried about this ? I don't think it's related to anything I did

### CODE REVIEW

**Comment by nktssh** [comment]
Sorry for bothering, but: any updates on this?
May I help somehow with this to be merged more quickly?

**Comment by mastilver** [comment]
@Ephys Do you mind rebasing your branch?
I think the tests are more stable now

**Comment by orther** [comment]
Is there anything Is there anything I can do to help push this along?

**Comment by SpainTrain** [comment]
ping-a-doodle-reno

**Comment by ljharb** [comment]
@Ephys would you mind rebasing this (on the command line, so there's no merge commits)?

@benmosher/@jfmengels, it'd be great if we could get a look at this within the next week or so, so it can be merged ❤️

**Comment by kusmierz** [comment]
@Ephys any chance to rebase it?

**Comment by Ephys** [comment]
@kusmierz Yes, it's on my backlog for this week :) Sorry very busy week as usual

**Comment by Ephys** [comment]
Apart from the (unrelated I hope) failed check, all should be good

**Comment by SpainTrain** [comment]
@Ephys FYI got a changelog conflict

**Comment by SpainTrain** [comment]
:crying_cat_face: dreams... :smile_cat:

File: src/core/importType.js [hunk 1]
```diff
@@ -29,7 +29,11 @@ export function isBuiltIn(name, settings) {
 
 function isExternalPath(path, name, settings) {
   const folders = (settings && settings['import/external-module-folders']) || ['node_modules']
-  return !path || folders.some(folder => -1 < path.indexOf(join(folder, name)))
+
+  // extract the part before the first / (redux-saga/effects => redux-saga)
```
Comment (ljharb) [inline src/core/importType.js]: what about scoped packages? Let's also add a test for `@foo/bar` or something.

**Comment by krvajal** [comment]
Is this expect to be merged at some point in the near future?

**Comment by ljharb** [comment]
@krvajal it's still waiting for @Ephys to address 
https://github.com/benmosher/eslint-plugin-import/pull/794#discussion_r159826950

**Comment by krvajal** [comment]
@ljharb it has been seven month already and no reply. You can either close the PR or allow someone to address the requested changes

**Comment by Ephys** [comment]
I'm very sorry to be the source of the delay. I had completely forgotten about this PR. 
I've updated my PR to add the necessary tests and I'll do my best to answer to future feedback in a timely fashion.

File: src/core/importType.js (hunk 1 above)
Comment (Ephys) [reply src/core/importType.js]: Done!

File: src/core/importType.js [hunk 2]
```diff
@@ -29,7 +29,11 @@ export function isBuiltIn(name, settings) {
...
+  const packageName = name.match(/([^/]+)/)[0]
```
Comment (echenley) [inline src/core/importType.js]: Can you use `const base = baseModule(name)` instead, like in `isBuiltIn`?

**Comment by echenley** [comment]
@Ephys This was approved a while back. Has this effort been abandoned?
