### PR TITLE
Fix import type determination for monorepo setup w/ webpack resolver

### LINKED ISSUE #1597: Incorrect behavior of import/order in a monorepo setup
Minimal reproduction of the bug and a detailed analysis of the cause: https://github.com/skozin/eslint-plugin-import-bug-repro.

## The bug

The `import/order` rule gives a false positive in a setup with the following conditions met:

1. The project uses [Yarn workspaces].
2. The packages inside the monorepo are scoped.
3. Webpack resolver is used.

## A quick example

Consider this code:

```js
import lodash from 'lodash';
import {sharedFn} from '@my-scope/package-a';

import {someFn} from './util';

export default {};
```

and this config:

```json
{
  "extends": [
    "plugin:import/errors",
    "plugin:import/warnings"
  ],
  "rules": {
    "import/order": ["error", {"newlines-between": "always"}]
  },
  "settings": {
    "import/resolver": "webpack",
    "import/external-module-folders": ["node_modules", "packages"]
  },
  "parserOptions": {
    "ecmaVersion": 2017,
    "sourceType": "module"
  }
}
```

The expected result is no errors being reported. However, this comes up instead:

```text
eslint-plugin-import-bug-repro/packages/package-b/index.js
  1:1  error  There should be at least one empty line between import groups        import/order
  4:1  error  `./util` import should occur before import of `@my-scope/package-a`  import/order
```

I've prepared a repo with a minimal reproduction and a detailed analysis of the cause: https://github.com/skozin/eslint-plugin-import-bug-repro.

## What happens

See [the repo with a reproduction](https://github.com/skozin/eslint-plugin-import-bug-repro#minimal-reproduction-of-a-bug-in-the-eslint-plugin-import-package) for a detailed explanation.

In short, the problem is that paths to scoped packages get considered as internal ones by the [`isExternalPath`] function even though the directory where these packages reside is added to the `import/external-module-folders` list in the config. Before #1294, this was not a problem since scoped packages were always considered as external ones, but after merging that PR the behavior changed and now scoped packages are considered external only if their resolved path is determined as external.

In turn, seemingly incorrect behavior of [`isExternalPath`] is caused by the logic inside it that doesn't only check that the resolved path to a package contains one of the `import/external-module-folders` as a subpath, but also that it includes the package name as a subpath. This is not true in the case of a monorepo with scoped packages since a path to a Yarn workspace containing the package contents doesn't need to include the package scope or even the package name as a subpath.

For example, in the described case the resolved path to `@my-scope/package-a` is `/path/to/the/project/packages/package-a/index.js` and it doesn't contain `@my-scope` part at all.

[Yarn workspaces]: https://yarnpkg.com/lang/en/docs/workspaces
[`isExternalPath`]: https://github.com/benmosher/eslint-plugin-import/blob/cd25d9d/src/core/importType.js#L27

### PR DESCRIPTION
**Pull request by skozin**
Fixes #1597.

This PR changes the logic of [`isExternalPath`] function so that it doesn't consider the import name. For a path to be external, it's now sufficient that it matches one of the items in the `import/external-module-folders` array specified in settings.

This is to support a setup where some of the modules are symlinked from `node_modules` into directories elsewhere in the project (called ["workspaces"] in Yarn terminology). For example, it's common to have a monorepo setup like this:

```
node_modules
  @my-scope
    core -> ../../packages/core
    utils -> ../../packages/utils
packages
  core
    package.json
    index.js
  utils
    package.json
    index.js
package.json
```

Usually, one wants these packages to be treated as external since they're normally installed from a registry. Intuitively, this should be achieved by adding `packages` to `import/external-module-folders` array. However, this didn't work in a project that uses the `webpack` resolver.

The reason is that `webpack` resolver returns a fully resolved path to the module's main file, e.g. for `@my-scope/core` it would be something like `/home/me/project/packages/core/index.js`. This path doesn't contain the package name, `@my-scope/core`, as a substring, so [`isExternalPath`] would consider this path as internal prior to the changes proposed in this PR. This led to the import itself being considered as internal, as after merging #1294 a scoped import is determined as external only if its path is external too.

Apart from removing the import name check from [`isExternalPath`], this PR also makes `import/external-module-folders` more strict. It won't match incomplete path segments anymore, so `some/path` won't match `/my/awesome/path` but will still match `/my/some/path` and `/my/some/path/index.js`. Also, if an item starts with a forward slash, it will be treated as an absolute path prefix, so `/home/me/project/packages` will only match the directory itself and everything inside it.

This PR doesn't break any existing tests, and I believe that it shouldn't break any existing setups either.

[`isExternalPath`]: https://github.com/benmosher/eslint-plugin-import/blob/cd25d9d/src/core/importType.js#L27
["workspaces"]: https://yarnpkg.com/lang/en/docs/workspaces/

### CODE REVIEW

**Comment by skozin** [comment]
CI build is probably failing due to the failing ESLint checks of the plugin source code and tests, but these checks were as well failing before this PR.

**Comment by skozin** [comment]
Hmm, not sure why Coveralls reports that coverage of `resolvers/node/index.js` decreased, I didn't change or remove any tests or code related to that resolver.

File: src/core/importType.js [hunk 1]
```diff
@@ -26,11 +25,17 @@ export function isBuiltIn(name, settings, path) {
 
 function isExternalPath(path, name, settings) {
   const folders = (settings && settings['import/external-module-folders']) || ['node_modules']
+  return !path || folders.some(folder => isSubpath(folder, path))
+}
 
-  // extract the part before the first / (redux-saga/effects => redux-saga)
-  const packageName = name.match(/([^/]+)/)[0]
+function isSubpath(subpath, path) {
+  const subpathRegExpSrc = escapeRegExp(subpath.replace(/[/]$/, ''))
```
Comment (ljharb) [inline src/core/importType.js]: i'm pretty concerned here about trying to manually regex escape and make a dynamic regex. is there a more reliable means of doing this test?

Comment (skozin) [reply src/core/importType.js]: There definitely is — I can do manual parsing and checking in a loop. I still don't think that the current way is unreliable, but I see how the more imperative solution might get better readability, so I'll go ahead with it.

Just in case, how the current way works:

1. Remove the trailing slash in case it's presented in an item.
2. In the case the item contains special regex symbols, [escape them](https://stackoverflow.com/a/3561711/804678).
3. Make a regex that checks if a path contains the item as a complete subpath:
3.a. If the item starts with a slash, make a regex that checks if a path contains the item between the start of the string and a path segment boundary (either end of the string or a slash).
3.b. Otherwise, make a regex that checks if a path contains the item between path segment boundaries (either start/end of the string or a slash).

But I see how this can be pretty unreadable from the code, so I'll re-write this using a loop instead.

File: src/core/importType.js [hunk 2]
```diff
@@ -26,11 +25,19 @@ export function isBuiltIn(name, settings, path) {
...
+function isSubpath(subpath, path) {
+  const normSubpath = subpath.replace(/[/]$/, '')
+  if (normSubpath.length === 0) {
+    return false
+  }
+  const left = path.indexOf(normSubpath)
+  const right = left + normSubpath.length
+  return left !== -1 &&
+        (left === 0 || normSubpath[0] !== '/' && path[left - 1] === '/') &&
+        (right >= path.length || path[right] === '/')
```
Comment (skozin) [inline src/core/importType.js]: @ljharb, how about this one? I did without any loops or dynamic regexes, so now it should be more clear what the thing does. If that's ok, I'll force-push overwriting the original commit.

Comment (ljharb) [reply src/core/importType.js]: looks great

Comment (skozin) [reply src/core/importType.js]: Awesome, I'll push in couple of hours then

Comment (skozin) [reply src/core/importType.js]: @ljharb, done! Please let me know if there's anything else that's needed in order for this to be merged. Thank you!

**Comment by ljharb** [comment]
@skozin i've rebased this and tweaked the test descriptions a bit, but tests are failing. Can you take a look?

**Comment by skozin** [comment]
@ljharb, thank you so much for assisting me and merging this!
