### PR TITLE
[Tests] `extensions`: add cases to verify `@/configs/chart` is treated as a package

### LINKED ISSUE #1851: Webpack alias not working
.eslintrc.js
```js
const path = require('path')

module.exports = {
  env: {
    node: true,
  },
  extends: ['plugin:vue/essential', 'eslint:recommended', '@vue/prettier'],
  parserOptions: {
    parser: 'babel-eslint',
  },
  plugins: ['import'],
  root: true,
  rules: {
    'import/exports-last': 'warn',
    'import/extensions': ['warn', 'ignorePackages'],
    'import/first': 'warn',
    'import/newline-after-import': 'warn',
    'import/no-duplicates': 'error',
    'import/no-relative-parent-imports': 'warn',
  },
  settings: {
    'import/resolver': {
      webpack: {
        config: {
          resolve: {
            alias: {
              '@': path.resolve('src'),
            },
          },
        },
      },
    },
  },
}
```
package.json
```
    "eslint-import-resolver-webpack": "^0.12.2",
    "eslint-plugin-import": "^2.22.0",
```
Result
image

### PR DESCRIPTION
**Pull request by wenfangdu**
Fixes #1851

Before this fix, `'import/extensions': ['warn', 'ignorePackages']` wouldn't warn `import chart from '@/configs/chart'`, this is an improvement over PR #1854.

### CODE REVIEW

File: tests/src/rules/extensions.js [hunk 1]
```diff
@@ -367,6 +368,11 @@ ruleTester.run('extensions', rule, {
           line: 4,
           column: 31,
         },
+        {
+          message: 'Missing file extension for "@/scoped/bav/import"',
+          line: 7,
+          column: 25,
+        },
```
Comment (ljharb) [inline tests/src/rules/extensions.js:375]: I'd expect `ignorePackages` to suppress this warning, since this is a package.

Comment (wenfangdu) [reply tests/src/rules/extensions.js]: I've edited the case, thanks.

File: tests/src/rules/extensions.js [hunk 2]
```diff
@@ -367,6 +368,11 @@ ruleTester.run('extensions', rule, {
           line: 4,
           column: 31,
         },
+        {
+          message: 'Missing file extension for "@/configs/chart"',
```
Comment (ljharb) [inline tests/src/rules/extensions.js:372]: again tho, this should never have a warning when `ignorePackages` is set, because it's a bare idenfier - a package.

Comment (wenfangdu) [reply tests/src/rules/extensions.js:372]: According to the [scoped packages doc](https://docs.npmjs.com/using-npm/scope.html), `@somescope/somepackagename` is a scoped package, whereas `@/foo/bar` is not.
Publishing `@/foo/bar` as an unscoped package is not allowed, so it's neither a scoped package nor an unscoped package.
image

Comment (ljharb) [reply tests/src/rules/extensions.js:372]: I agree that it isn't "a scoped package", but since it doesn't start with `.` or `/`, it is a "bare identifier", which is always "a package" - packages aren't just "publishable packages", they're "anything with a bare identifier".

Comment (ljharb) [reply tests/src/rules/extensions.js:372]: Circling back on this - `@` is a package here (just not a publishable one), so I think this should be ignored when `ignorePackages` is enabled.

**Review by ljharb — APPROVED** [review]
I've rebased this to only include updated test cases, since this is already working as intended.
