### PR TITLE
Fix crash due to export * with no-unused-modules

### LINKED ISSUE #1382: import/no-unused-modules crashes linter
**Error:** TypeError: Error while loading rule 'import/no-unused-modules': Cannot read property 'path' of null

**.eslintrc**
```json
{
  "extends": [
    "react-app",
    "plugin:prettier/recommended",
    "plugin:cypress/recommended",
    "eslint:recommended",
    "plugin:import/errors",
    "plugin:import/warnings"
  ],
  "settings": {
    "import/resolver": {
      "node": {
        "moduleDirectory": ["node_modules", "src"]
      }
    }
  },
  "globals": {
    "_": true,
    "less": true,
    "moment": true,
    "cypress/globals": true
  },
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 2018,
    "ecmaFeatures": {
      "impliedStrict": true,
      "classes": true
    }
  },
  "env": {
    "browser": true,
    "node": true,
    "jest": true
  },
  "rules": {
    "no-console": ["error", { "allow": ["warn", "error"] }],
    "array-callback-return": "error",
    "no-unused-vars": "warn",
    "eqeqeq": "error",
    "no-eq-null": "error",
    "no-lone-blocks": "error",
    "no-magic-numbers": "warn",
    "no-shadow": "warn",
    "max-depth": ["error", 3],
    "import/order": [
      "error",
      { "groups": ["builtin", "external", "internal", "index", "parent", "sibling"], "newlines-between": "always" }
    ],
    "import/newline-after-import": ["error"],
    "import/no-unused-modules": [1, { "unusedExports": true }]
  }
}
```

### PR DESCRIPTION
**Pull request by Taranys**
fix #1382 

After investigating, It comes from this line
https://github.com/benmosher/eslint-plugin-import/blob/5e143b23f3b89096e1b6a268af723f60c1ecb22f/src/ExportMap.js#L316

In my case, `export * from 'redux-starter-kit'` is not detected as unambigous and it `return null` which crash no-unused-modules

I didn't find any good way to test it. I'm looking forward for some advices on how I can test this issue :)

### CODE REVIEW

File: src/rules/no-unused-modules.js [hunk 1]
```diff
@@ -87,8 +87,13 @@ const prepareImportsAndExports = (srcFiles, context) => {
 
       // dependencies === export * from
       const currentExportAll = new Set()
-      dependencies.forEach(value => {
-        currentExportAll.add(value().path)
+      dependencies.forEach(getDependency => {
+        const dependency = getDependency()
+        if(dependency === null) {
```
Comment (ljharb) [inline src/rules/no-unused-modules.js]:
```suggestion
        if (dependency === null) {
```

**Comment by soryy708** [comment]
Is this related? https://github.com/benmosher/eslint-plugin-import/issues/1260

**Comment by Taranys** [comment]
@soryy708 Don't seems related to me. 

From my investigation, it seems that common-js compiled files are not properly managed if you do an `export *'`

**Comment by Taranys** [comment]
@ljharb I added a test :)

File: tests/files/no-unused-modules/cjs.js [hunk 2]
```diff
@@ -0,0 +1,7 @@
+// Simple import extracted from 'redux-starter-kit' compiled file
+
+function isPlain(val) {
+  return typeof val === 'undefined' || val === null || typeof val === 'string' || typeof val === 'boolean' || typeof val === 'number' || Array.isArray(val) || isPlainObject(val);
```
Comment (ljharb) [inline tests/files/no-unused-modules/cjs.js]:
```suggestion
  return true;
```
There's no need to have actual logic here.

**Comment by ljharb** [comment]
@Taranys i rebased this, but tests are failing.
