### PR TITLE
Fix overwriting of dynamic import() CallExpression

### LINKED ISSUE #1035: Lint Dynamic Imports for no-unresolved
For code-splitting in our app we have
```
import(/* webpackChunkName: "WelcomePage" */ "./components/WelcomePage")
```

However, we don't get the same awesome eslint error if that path doesn't exist. It would be great to have that linted as well.

### LINKED ISSUE #1166: no-cycle rule not working with babel-eslint parser
Here is a simple repro:

package.json
```
{
  "dependencies": {
    "babel-eslint": "^9.0.0",
    "eslint": "^5.4.0",
    "eslint-plugin-import": "^2.14.0"
  }
}
```
.eslintrc
```
{
	parser: "babel-eslint",
	parserOptions: {
		sourceType: 'module',
	},
	plugins: ['import'],
	rules: { 'import/no-cycle': 'error' },
}
```

a.js
```
import B from './b';
export default "A" + B;
```

b.js
```
import A from './a';
export default A + "B";
```

No error is found by eslint but if default parser is used (by removing line `parser: "babel-eslint",`) then `no-cycle` errors are found in each file.

Is it the expected behaviour ? An issue with `eslint-plugin-import` ? An issue with `babel-eslint` ?

### PR DESCRIPTION
**Pull request by vikr01**
Closes #1035
Closes #1166

So turns out, dynamic imports were already supported in `moduleVisitor` but they were being overwritten if `commonjs` or `amd` options were set.

- Fixed by saving the current `CallExpression` and including it in the function that's overwriting it.
- Added test cases for `import()` in rules using the `moduleVisitor`. Not sure why, but I couldn't get the `no-cycle` rule to throw errors with `import()`.
- Fixes issues with parser `babel-eslint` not working with `no-cycle`, due to the "flow workaround" for `eslint@<5`

This might be breaking for some users, though.

Also since `import()` can work with URLs, maybe we should use something like [`isURL` from `validator`](https://github.com/chriso/validator.js#validators) to ignore URL imports?

### CODE REVIEW

File: tests/src/rules/no-cycle.js [hunk 1]
```diff
@@ -88,6 +93,16 @@ ruleTester.run('no-cycle', rule, {
       code: 'import { bar } from "./depth-three-indirect"',
       errors: [error(`Dependency cycle via ./depth-two:1=>./depth-one:1`)],
     }),
+    // test({
```
Comment (ljharb) [inline tests/src/rules/no-cycle.js]: i assume these should be uncommented

Comment (vikr01) [reply tests/src/rules/no-cycle.js]: It should. Errors for `import()` with `no-cycle` aren't working because of [the workaround for `flow` import resolution in `eslint@<5.x`](https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/no-cycle.js#L37).

Comment (ljharb) [reply tests/src/rules/no-cycle.js]: That seems like something worth fixing. Why would a flow workaround impact `import()`, which is actual JS?

Comment (ljharb) [reply tests/src/rules/no-cycle.js]: That seems like something worth fixing. Why would a flow workaround impact `import()`, which is actual JS?

Comment (ljharb) [reply tests/src/rules/no-cycle.js]: That seems like something worth fixing. Why would a flow workaround impact `import()`, which is actual JS?

Comment (ljharb) [reply tests/src/rules/no-cycle.js]: That seems like something worth fixing. Why would a flow workaround impact `import()`, which is actual JS?

Comment (vikr01) [reply tests/src/rules/no-cycle.js]: Fixed by using `importer.importKind` instead of `sourceNode.parent && sourceNode.parent.importKind`. Would that break anything? I added a few more tests for `no-cycle` that import multiple variables together just to be careful.

File: utils/moduleVisitor.js [hunk 2]
```diff
@@ -91,12 +91,15 @@ exports.default = function visitModules(visitor, options) {
   }
 
   if (options.commonjs || options.amd) {
+    const currentCallExpression = visitors['CallExpression']
```
Comment (ljharb) [inline utils/moduleVisitor.js]:
```suggestion
    const currentCallExpression = visitors.CallExpression
```

File: utils/moduleVisitor.js [hunk 3]
```diff
@@ -91,12 +91,15 @@ exports.default = function visitModules(visitor, options) {
...
     visitors['CallExpression'] = function (call) {
```
Comment (ljharb) [inline utils/moduleVisitor.js]: i know this predates your PR, but:
```suggestion
    visitors.CallExpression = (call) => {
```

File: utils/moduleVisitor.js [hunk 4]
```diff
@@ -91,12 +91,15 @@ exports.default = function visitModules(visitor, options) {
...
+      if (currentCallExpression) currentCallExpression(call)
       if (options.commonjs) checkCommon(call)
       if (options.amd) checkAMD(call)
     }
   }
 
+
```
Comment (ljharb) [inline utils/moduleVisitor.js]:
```suggestion
```

File: utils/moduleVisitor.js (hunk 3 above)
Comment (vikr01) [reply utils/moduleVisitor.js]: I agree, but this seems to have done throughout the project.

See:
- [`src/rules/no-commonjs`](https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/no-commonjs.js#L88)
- [`src/rules/default`](https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/default.js#L36)

If we do it for this case, shouldn't we do it for all of them?

File: tests/src/rules/no-cycle.js (hunk 1 above)
Comment (vikr01) [reply tests/src/rules/no-cycle.js]: Worth noting - `no-cycle` was also not working for static `import` with `babel-eslint` because of this, which is why I added a test case for static `import` with the `babel-eslint` parser.

**Comment by vikr01** [comment]
[Here](https://ci.appveyor.com/project/vikr01/eslint-plugin-import/builds/20370307)'s a passing appveyor on the branch of my fork.

**Comment by edmorley** [comment]
@ljharb thank you for reviewing this and the related #1231.
Do we need a second reviewer, if so, who is best to ask? :-)

**Comment by corradio** [comment]
any updates here? Would be great to have this merged
