### PR TITLE
[Fix] `export`/TypeScript: properly detect export specifiers as children of a TS module block

### LINKED ISSUE #1773: [import/export] "Multiple default exports" in Typescript ambient module declarations
If a Typescript file (or, more likely, a `.d.ts` file) has several ambient module declarations with default exports, sometimes they're mistakenly reported as "multiple default exports".

```TS
declare module "a" {
  function a(): void;
  export {a as default};
}

declare module "b" {
  function b(): void;
  export {b as default};
}
```

```YAML
plugins:
  - import
rules:
  import/export: error
```

Here's a case where that doesn't happen, though:

```TS
declare module "a" {
  export default function a(): void;
}

declare module "b" {
  export default function b(): void;
}
```

### PR DESCRIPTION
**Pull request by andreubotella**
Fixes #1773

### CODE REVIEW

File: src/rules/export.js [hunk 1]
```diff
@@ -87,7 +87,11 @@ module.exports = {
     return {
       'ExportDefaultDeclaration': (node) => addNamed('default', node, getParent(node)),
 
-      'ExportSpecifier': (node) => addNamed(node.exported.name, node.exported, getParent(node)),
+      'ExportSpecifier': (node) => addNamed(
+        node.exported.name,
+        node.exported,
+        getParent(node.parent)
+      ),
```
Comment (ljharb) [inline src/rules/export.js:95]: i'm a bit confused; all this is doing is reformatting. do these tests pass on master?

Comment (andreubotella) [reply src/rules/export.js:95]: It changes `getParent(node)` to `getParent(node.parent)`. That would've been more obvious if I hadn't reformatted.

Comment (andreubotella) [reply src/rules/export.js:95]: Bump

**Review by ljharb — APPROVED** [review]
