### PR TITLE
[Generic Import Callback] Make callback for all import once in rules

### LINKED ISSUE #1230: import/extensions doesn't work for require('./file-without-extension')
See reproduction details at https://github.com/balupton/eslint-issue-import-extensions

---

get started:

```
git clone https://github.com/balupton/eslint-issue-import-extensions.git
cd eslint-issue-import-extensions
npm install
```

run the test:

```
npm test
```

notice that there was no complaint about:

``` js
const result = require('./module')
```

inside `./source/index.js`

### PR DESCRIPTION
**Pull request by ljqx**
This PR fixes #1230.

Not only for `import/extensions`, this PR also adds supports of all 
1) `ImportDeclaration`, 
2) `ExportNamedDeclaration`, 
3) `ExportAllDeclaration`, 
4) static require `CallExpression` 

for rules `import/extensions`, `import/max-dependencies`, `import/no-extraneous-dependencies`, `import/no-internal-modules`, `import/no-nodejs-modules`, `import/no-restricted-paths`, `import/no-self-import`, `import/no-webpack-loader-syntax` by abstracting out the common part for these callbacks.

Tests are added for `import/extensions`.

### CODE REVIEW

File: src/core/addForGenericImport.js [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+
+export default function addForGenericImport(allCallbacks, genericImportCallback) {
+  const {
+    ImportDeclaration = noop,
+    ExportNamedDeclaration = noop,
+    ExportAllDeclaration = noop,
+    CallExpression = noop,
+  } = allCallbacks
+
+  return Object.assign({}, allCallbacks, {
```
Comment (ljharb) [inline src/core/addForGenericImport.js]: can this use object spread?

Comment (ljqx) [reply src/core/addForGenericImport.js]: Sure :)

**Comment by ljharb** [comment]
@ljqx i've rebased this, but some tests are failing now. could you take a look?

**Comment by brodybits** [comment]
This update could help with a lint task on Prettier. Is there anything we can do to help get this update finalized and ready for an upcoming release?

I did take a quick look at the build failures from last year, found messages like this:

> AssertionError [ERR_ASSERTION]: A fatal parsing error occurred: Parsing error: Export 'bar' is not defined

I wonder if something in the stack had become stricter over time.

**Review by benmosher — APPROVED** [review]
sorry it's 23 months later, but LGTM 👍🏼😅

**Comment by ljharb** [comment]
@ljqx any chance you'd be able to rebase this? it's a bit hairy.

**Comment by ljqx** [comment]
Hi, Ben and Jordan, updated, and replaced the introduced helper function with existing `eslint-module-utils/moduleVisitor`

**Comment by ljqx** [comment]
It looks AppVeyor would always fail on WSL: 
>> wsl : gpg: can't connect to the agent: IPC connect call failed

This should not related to this change.

I'll wait for Travis result.

**Comment by ljqx** [comment]
The travis and coverage have passed :)
