### PR TITLE
Make aggregating modules valid in group-exports

### LINKED ISSUE #1471: group-exports aggregating modules should be valid
I would like to make [aggregating modules](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export) valid when using the `group-exports` rule.

**Use-case**
When aggregating modules in a single file the `group-exports` rule fails on because of multiple export declarations. This makes it invalid to re-export submodules from the root of a module.

**Steps to reproduce**
- create a file with the following exports
```js
export { default as module1 } from 'module-1'
export { default as module2 } from 'module-2'
```
- validate the file using the `group-exports` rule

**Expected results**
No linting error.

**Actual result**
Linting error.

### PR DESCRIPTION
**Pull request by atikenny**
Fixes #1471

### CODE REVIEW

File: tests/src/rules/group-exports.js [hunk 1]
```diff
@@ -45,6 +45,10 @@ ruleTester.run('group-exports', rule, {
       // test
       export default {}
     ` }),
+    test({ code: `
+      export { default as module1 } from './module-1'
+      export { default as module2 } from './module-2'
```
Comment (ljharb) [inline tests/src/rules/group-exports.js]: let's add another test to ensure that this:
```jsx
       export { a as module1 } from './module-1'
       export { b as module2 } from './module-1'
```
still warns?

File: docs/rules/group-exports.md [hunk 2]
```diff
@@ -69,6 +69,12 @@ export const first = true
 export const second = true
 ```
 
+```js
+// Aggregating exports from the same module -> ok
```
Comment (ljharb) [inline docs/rules/group-exports.md]: this should be "not ok", since you can do `export { module1, module2 } from 'module-1'`

File: src/rules/group-exports.js [hunk 3]
```diff
@@ -86,6 +95,18 @@ function create(context) {
         })
       }
 
+      // Report multiple `aggregated exports` from the same module (ES2015 modules)
+      Object.keys(nodes.sources)
```
Comment (ljharb) [inline src/rules/group-exports.js]: You can use the object.values package here, instead of having to use Object.keys.
