### PR TITLE
fix: import/no-cycle triggering errors for Flow imports

### LINKED ISSUE #1343: import/no-cycle should not trigger for Flow imports
This is a regression of #1098 (fix in PR #1126) that was re-introduced in v2.17.0.

v2.16.0 works as expected. v2.17.2 still has this regression.

### PR DESCRIPTION
**Pull request by maxmalov**
The changes fix a complex circular dependency where Flow type imports are transient dependencies of the checked module. Basically such imports can be ignored too since they will be stripped anyway

Fixes #1343

### CODE REVIEW

File: tests/files/cycles/flow-types.js [hunk 1]
```diff
@@ -0,0 +1,5 @@
+// @flow
+
+import type { FooType } from './flow-types-depth-two';
```
Comment (102) [inline tests/files/cycles/flow-types.js]: Should this also work for `import { type FooType } ...` syntax?

Comment (maxmalov) [reply tests/files/cycles/flow-types.js]: This complicates things a little, since import kind becomes the value. I didn’t discover how to identify such type imports yet

**Comment by dominicfraser** [comment]
@102 @maxmalov - could we have an update on the status of this PR? :)

**Comment by maxmalov** [comment]
@dominicfraser yeah, the fix supposed to handle both type import variants `import type { Foo }` and `import { type Bar }`
