### PR TITLE
[import/order] Fix incorrect import reordering

### LINKED ISSUE #1252: autofix "import/order" will produce new problems?
env:
os: macos 10.14.2
node: 10.15.0
npm: 6.4.1
eslint: local 5.11.1

package.json
```json
{
  "name": "testeslint",
  "version": "0.0.1",
  "scripts": {
    "eslint": "eslint --ext .js .",
  },
  "devDependencies": {
    "eslint": "^5.11.1",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-plugin-import": "^2.14.0",
    "express": "^4.16.4"
  }
}
```
.eslintrc.js
```js
module.exports = {
    "extends": "airbnb-base"
};
```

a.js
```js
const env = require('./config');

Object.keys(env);

const http = require('http');

function express() {}

http.createServer(express());
```

b.js
```js
const env = require('./config');

Object.keys(env);

const http = require('http');
const express = require('express');

http.createServer(express());
```

```bash
$ npm run eslint

> testeslint@0.0.1 eslint /Users/hbshun/testeslint
> eslint --ext .js .

/Users/hbshun/testeslint/a.js
  5:14  error  `http` import should occur before import of `./config`  import/order

/Users/hbshun/testeslint/b.js
  1:13  error  `./config` import should occur after import of `express`                       import/order
  6:17  error  'express' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies

✖ 3 problems (3 errors, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

```bash
$ npm run eslint -- --fix

> testeslint@0.0.1 eslint /Users/hbshun/testeslint
> eslint --ext .js . "--fix"

/Users/hbshun/testeslint/a.js
  5:14  error  `http` import should occur before import of `./config`  import/order

/Users/hbshun/testeslint/b.js
  2:13  error  'env' was used before it was defined                                           no-use-before-define
  5:17  error  'express' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies

✖ 3 problems (3 errors, 0 warnings)
```

Now, b.js:

```js

Object.keys(env);

const http = require('http');
const express = require('express');
const env = require('./config');

http.createServer(express());
```

[repo for test](https://github.com/hbshun/testeslint)

### PR DESCRIPTION
**Pull request by tihonove**
Closes #1252

### CODE REVIEW

**Comment by tihonove** [comment]
I have no idea why ci builds failed. Seams like build for eslint5 broken.

File: tests/src/rules/order.js [hunk 1]
```diff
@@ -1153,7 +1153,91 @@ ruleTester.run('order', rule, {
...
+        ruleId: 'order',
+        message: '`./local` import should occur after import of `global2`',
+      }],
+    }),
+    // reorder fix cannot cross function call on moving below #3
+    test({
+      code: `
+        const local1 = require('./local1');
+        const local2 = require('./local2');
+        const local3 = require('./local3');
```
Comment (ljharb) [inline tests/src/rules/order.js]: All of these new tests start with each group already ordered; can we unordered them, and show that the autofixer properly orders them?

Comment (tihonove) [reply tests/src/rules/order.js]: @ljharb Great! I wrote requested tests and found some cases that autofixer dont order imports inside group. I inspected code and find out that ability to reorder imports inside group requires great rework of rule code (another issue?). 

This PR just fix a bug in current algorithm of rule. I suggest use this PR as quick fix, and create another (less critical) issue to fix sorting inside groups.

Comment (ljharb) [reply tests/src/rules/order.js]: In that case I'd still like to see the test cases show what it *currently* does when it starts out out of order; perhaps with additional cases instead of changing these?

Comment (tihonove) [reply tests/src/rules/order.js]: Added few tests with unordered groups around function call, including cases with not fully reordered groups after applying autofix

**Comment by ljharb** [comment]
@tihonove can you rebase this?

**Comment by tilgovi** [comment]
Anything I can do to help?

File: tests/src/rules/order.js [hunk 2]
```diff
@@ -1153,7 +1153,137 @@ ruleTester.run('order', rule, {
...
+
+        fn_call();
+      `,
+      output: `
+        const local = require('./local');
+
+        fn_call();
+
+        const global1 = require('global1');
+        const global2 = require('global2');
```
Comment (ljharb) [inline tests/src/rules/order.js]: without the fix, i get this output (and a test failure):
```diff
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Output is incorrect.
+ expected
- actual
 
+        const local = require('./local');
 
         fn_call();
 
         const global1 = require('global1');
         const global2 = require('global2');
-        const local = require('./local');
 
         fn_call();
```

File: tests/src/rules/order.js [hunk 3]
```diff
@@ -1153,7 +1153,137 @@ ruleTester.run('order', rule, {
...
+      `,
+      errors: [{
+        ruleId: 'order',
+        message: '`./local` import should occur after import of `global2`',
+      }],
+    }),
+    // reorder fix cannot cross function call on moving below #2
+    test({
+      code: `
+        const local = require('./local');
```
Comment (ljharb) [inline tests/src/rules/order.js]:
```diff
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Output is incorrect.
+ expected
- actual
 
+        const local = require('./local');
         fn_call();
         const global1 = require('global1');
         const global2 = require('global2');
-        const local = require('./local');
 
         fn_call();
```

File: tests/src/rules/order.js [hunk 4]
```diff
@@ -1153,7 +1153,137 @@ ruleTester.run('order', rule, {
...
+      `,
+      errors: [{
+        ruleId: 'order',
+        message: '`./local` import should occur after import of `global2`',
+      }],
+    }),
+    // reorder fix cannot cross function call on moving below #3
+    test({
+      code: `
+        const local1 = require('./local1');
```
Comment (ljharb) [inline tests/src/rules/order.js]:
```diff
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Output is incorrect.
+ expected
- actual
 
+        const local1 = require('./local1');
         const local2 = require('./local2');
         const local3 = require('./local3');
         const local4 = require('./local4');
         fn_call();
         const global2 = require('global2');
         const global3 = require('global3');
         const global4 = require('global4');
         const global5 = require('global5');
-        const local1 = require('./local1');
         fn_call();
```

File: tests/src/rules/order.js [hunk 5]
```diff
@@ -1153,7 +1153,137 @@ ruleTester.run('order', rule, {
...
+        '`./local1` import should occur after import of `global5`',
+        '`./local2` import should occur after import of `global5`',
+        '`./local3` import should occur after import of `global5`',
+        '`./local4` import should occur after import of `global5`',
+      ],
+    }),
+    // reorder fix cannot cross function call on moving below
+    test(withoutAutofixOutput({
+      code: `
+        const local = require('./local');
```
Comment (ljharb) [inline tests/src/rules/order.js]:
```diff
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Output is incorrect.
+ expected
- actual
 
+        const local = require('./local');
         const global1 = require('global1');
         const global2 = require('global2');
         fn_call();
         const global3 = require('global3');
-        const local = require('./local');
 
         fn_call();
```

File: tests/src/rules/order.js [hunk 6]
```diff
@@ -1153,7 +1153,137 @@ ruleTester.run('order', rule, {
...
+    })),
+    // reorder fix cannot cross function call on moving below
+    // fix imports that not crosses function call only
+    test({
+      code: `
+        const local1 = require('./local1');
+        const global1 = require('global1');
+        const global2 = require('global2');
+        fn_call();
+        const local2 = require('./local2');
```
Comment (ljharb) [inline tests/src/rules/order.js]:
```diff
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Output is incorrect.
+ expected
- actual
 
+        const local1 = require('./local1');
         const global1 = require('global1');
         const global2 = require('global2');
         fn_call();
-        const local2 = require('./local2');
         const global3 = require('global3');
         const global4 = require('global4');
-        const local1 = require('./local1');
+        const local2 = require('./local2');
 
         fn_call();
```

File: tests/src/rules/order.js [hunk 7]
```diff
@@ -1166,6 +1296,33 @@ ruleTester.run('order', rule, {
         message: '`fs` import should occur before import of `async`',
       }],
     })),
+    // reorder fix cannot cross function call on moving below (from #1252)
+    test({
+      code: `
+        const env = require('./config');
+
+        Object.keys(env);
```
Comment (ljharb) [inline tests/src/rules/order.js]:
```diff
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Output is incorrect.
+ expected - actual
 
+        const env = require('./config');
 
         Object.keys(env);
 
         const http = require('http');
         const express = require('express');
-        const env = require('./config');
 
         http.createServer(express());
```
