### PR TITLE
Fixed flow types imports

### LINKED ISSUE #921: import/named doesn't detect Flow Opaque types in flow comments
Hi all!

When using flow [opaque types](https://flow.org/en/docs/types/opaque-types/) (new in https://github.com/facebook/flow/releases/tag/v0.51.0) via flow [comments](https://flow.org/en/docs/types/comments/) The `import/named` rule doesn't detect the exported types.

Ex:

### Foo.js
```javascript
// @flow

/*::
export opaque type Foo = string;
*/

export const makeFoo = (): Foo => 'new foo';
```

### UseFoo.js
```javascript
// @flow

import { type Foo } from './Foo'; // Foo not found in './Foo' (import/named)
```

A weird workaround is to remove `makeFoo` from `Foo.js` and that will fix the linter rule. Don't know why that is. It's also not a good workaround since that makes the opaque type useless.

### LINKED ISSUE #1115: import/named doesn't ignore Flow identifier syntax type import
"Identifier syntax":
```javascript
// @flow
import { type Dispatch } from 'redux';
```
Gives following error:
```
2:15  error    Dispatch not found in 'redux'        import/named
```
Whilst the "declaration syntax":
```javascript
// @flow
import type { Dispatch } from 'redux';
```
Generates no error.

This is especially annoying for users that use the [`flowtype/type-import-style`](https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-rules-type-import-style) rule with the default setting ("identifier") and run ESLint with `--fix`, since that rule will automatically change the syntax, which then triggers `import/named`.

The point of the identifier syntax is to combine type and value imports in the same statement, e.g.

```javascript
// @flow
import { configureStore, type Dispatch } from 'redux';
```

The [docs for this rule](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/named.md) state:
> Note that type imports, as used by Flow, are always ignored.

So I think this is a bug. Can we ignore the identifier syntax for this rule also?

### PR DESCRIPTION
**Pull request by syymza**
#1057 has fixed #921 for the basic case, in which an import is the only thing imported from a specific file.
Sometimes types and functions/classes need to be imported from the same file. This PR fixes also that specific instance:
```
import  { type MyOpaqueType, MyClass } from "./flowtypes"',
```

I have added some tests for all these cases

Fixes #1115.

### CODE REVIEW

File: src/rules/named.js [hunk 1]
```diff
@@ -30,6 +30,9 @@ module.exports = {
       node.specifiers.forEach(function (im) {
         if (im.type !== type) return
 
+        // ignore type imports
+        if(im.importKind === 'type') return
```
Comment (ljharb) [inline src/rules/named.js]: space after `if`?

Comment (syymza) [reply src/rules/named.js]: added

**Comment by syymza** [comment]
@benmosher Added the requested test.
`node.importKind === 'type'` checks the imports having the `type` word outside of the `{}` specs. For this reason it cannot be removed, otherwise the other tests I have added in this PR will fail

**Comment by syymza** [comment]
🙄

**Comment by fizwidget** [comment]
Hey @benmosher, could you take another look at this one when you get a chance? Would love to see it merged 🙂

**Comment by bstuff** [comment]
Does this work when there are comments in imported module like:
foo.js:
```
/* flow-include
  export type Foo = string | number;
*/

```

bar.js:
```
import { type Foo } from './foo';
```
?

**Comment by ljharb** [comment]
@bstuff not sure; can you file a new issue if it doesn’t work?

**Comment by syymza** [comment]
@bstuff it should :)
