### PR TITLE
[fix] `export`: false positive for typescript overloads

### LINKED ISSUE #1357: import/export: false positives for typescript overloads
Minimal example to reproduce (not a sensible use case for overloads, but anyway):

```
export function consume(val: number): void;
export function consume(val: string): void;
export function consume(val: number | string): void {
    // Do something.
}
```

All three `consume` will be annotated with ` error  Multiple exports of name 'consume'   import/export`.

### PR DESCRIPTION
**Pull request by golopot**
Fixes #1357.

Fixes false positives like this: 
```ts
export function foo(a: number) {}
export function foo(a: string) {}
 ```

### CODE REVIEW

File: src/rules/export.js [hunk 1]
```diff
@@ -34,6 +47,7 @@ module.exports = {
 
   create: function (context) {
     const namespace = new Map([[rootProgram, new Map()]])
+    const isTypescriptFile = /\.ts|\.tsx$/.test(context.getFilename())
```
Comment (ljharb) [inline src/rules/export.js]: this seems like something that would need to be determined based on parser settings, not hardcoded extensions - also, what about flow?

File: src/rules/export.js [hunk 2]
```diff
@@ -24,6 +24,19 @@ ambient namespaces:
 const rootProgram = 'root'
 const tsTypePrefix = 'type:'
 
+/**
+ * Detect function overloads like:
+ * ```js
+ * export function foo(a: number) {}
+ * export function foo(a: string) {}
```
Comment (ljharb) [inline src/rules/export.js]: don’t overloads look like:
```suggestion
 * export function foo(a: string);
```
ie, the body is supposed to be omitted?

File: src/rules/export.js (hunk 1 above)
Comment (golopot) [reply src/rules/export.js]: 1. Will it suffice to do something like `\/@typescript-eslint\/parser\/.test(context.parserPath)`?(`context.parserPath` is like `/home/some-user/some-project/node_modules/@typescript-eslint/parser/dist/parser.js`) 2. It seems that flow does not accept function overload like the case here.

Comment (ljharb) [reply src/rules/export.js]: that would force people to install the typescript parser even if they weren’t using typescript, i think - ideally we’d find a more reliable mechanism than “its typescript” to handle this case.

Comment (golopot) [reply src/rules/export.js]: Just find out find that these function nodes without body has node type `TSDeclareFunction`. Therefore I change the bail out logic to `some nodes is TSDeclareFunction && every nodes is TSDeclareFunction or FunctionDeclaration`.

File: src/rules/export.js (hunk 2 above)
Comment (golopot) [reply src/rules/export.js]: Sure.

File: src/rules/export.js [hunk 3]
```diff
@@ -137,7 +141,7 @@ module.exports = {
           for (let [name, nodes] of named) {
             if (nodes.size <= 1) continue
 
-            if (isTypescriptFile && isTypescriptFunctionOverloads(nodes)) continue
+            if (isTypescriptFunctionOverloads([...nodes])) continue
```
Comment (benmosher) [inline src/rules/export.js]: why the spread into an array? is `nodes` not an Array, just an iterable? `Set` maybe? if so I might `Array.from(nodes)` to make it a little clearer. but definitely nitpicking, this is a great improvement

Comment (ljharb) [reply src/rules/export.js]: why not pass the Set in directly, and convert it inside the function?

Comment (golopot) [reply src/rules/export.js]: Ready for review

File: src/rules/export.js [hunk 4]
```diff
@@ -24,6 +24,24 @@ ambient namespaces:
...
+ * export function foo(a: number);
+ * export function foo(a: string);
+ * export function foo(a: number|string) { return a; }
+ * ```
+ * @param {Set<Object>} nodes
+ * @returns {boolean}
+ */
+function isTypescriptFunctionOverloads(nodes) {
+  return Array.from(nodes).some(node => node.parent.type === 'TSDeclareFunction') &&
+    Array.from(nodes).every(node => (
```
Comment (ljharb) [inline src/rules/export.js]: let's definitely not do Array.from twice. maybe something like this for the body of the function?
```js
const types = new Set(Array.from(nodes, node => node.parent.type));
if (!types.has('TSDeclareFunction') || types.size > 2) {
  return false;
}
return types.size === 1 || types.has('FunctionDeclaration');
```

Comment (golopot) [reply src/rules/export.js]: I end up with this:
```js
const types = new Set(Array.from(nodes, node => node.parent.type))
return types.size === 2 && types.has('TSDeclareFunction') && types.has('FunctionDeclaration')
```
The case when `types` is the same as `new Set("TSDeclareFunction")` is when the function lacks implementation, which is a tsc error.

Comment (ljharb) [reply src/rules/export.js]: That isn't the same logic though - your current logic allows it to be only "TSDeclareFunction". Functions don't need an implementation in tsc if they're just defining a type overload.

Comment (golopot) [reply src/rules/export.js]: That case is a tsc error https://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBAMwK4DsDGMCWEWIBQCUQA . And for the purpose of this rule, that case does not matter.
